rvm:
  - 1.9.3
  - 2.0.0
gemfile:
  - spec/gemfiles/Gemfile.ar-3.2
  - spec/gemfiles/Gemfile.ar-4.0
  - spec/gemfiles/Gemfile.ar-edge

before_script:
  - mysql -e 'create database rescue_from_duplicate;'
  - psql -c 'create database rescue_from_duplicate;' -U postgres

env:
  - POSTGRES=1
  - MYSQL=1

matrix:
  allow_failures:
    - gemfile: gemfiles/Gemfile.ar-edge
